# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83b509d6f90f862ea7e5397fd70e5392cf2645d0c4a6d9a43269c470c2818fdc96baa7ef7c17c2a6143b98b5517bd328bffcbe3d333be738d0c1c7ca35f4278a

test:
  secret_key_base: 86eb94685ed41d88130ae4d3b8cd04fa91ea942b294008cd1ba38829244f5dbc721bd8f09ff4b2b4b97e481ce7165470c6b5ecef0c87132d4d9af1ddca3bd125

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
